# Copyright (C) 2024 Atym Incorporated. All rights reserved.
# Atym Container Appplication File

version: '4'

services:

  blinky_service:
    image: senors:latest 
    resource:
      heapSize: 4096
    environment:
      - ENV="NULL"