# Copyright (C) 2024 Atym Incorporated. All rights reserved.
# Atym container image definition

version: '1'

name: subscriber
binaries:
  - path: build/subscriber.wasm

config:
  environment:
    - INTERVAL=500
  permissions:
    - console
    - LED