# Copyright (C) 2025 Atym Incorporated. All rights reserved.
# Atym container image definition

version: '1'

name: blinky
binaries:
  - path: build/blinky.wasm

config:
  environment:
    - INTERVAL=500
  permissions:
    - console
    - LED